cxx_compiler:
  - clang_bootstrap  # [osx]
  - gxx              # [linux]
  - vs2019           # [win]
c_compiler:
  - clang_bootstrap  # [osx]
  - gcc              # [linux]
  - vs2019           # [win]

c_compiler_version:     # [osx]
  - "*"                 # [osx]
cxx_compiler_version:   # [osx]
  - "*"                 # [osx]

MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
- '10.14'                  # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
- '10.14'                  # [osx and x86_64]

channel_targets:
  - conda-forge llvm_rc

channel_sources:
  - conda-forge/label/llvm_rc,conda-forge
