cxx_compiler:
  - clang_bootstrap  # [osx]
  - gxx              # [linux]
  - vs2017           # [win]
c_compiler:
  - clang_bootstrap  # [osx]
  - gcc              # [linux]
  - vs2017           # [win]
vc:
  - 14
c_compiler_version:     # [osx]
  - "*"                 # [osx]
cxx_compiler_version:   # [osx]
  - "*"                 # [osx]

MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
- '10.13'                  # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
- '10.13'                  # [osx and x86_64]
