{% set version = "20.0.0.dev4" %}

package:
  name: lld
  version: {{ version }}

source:
  # url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-{{ version.replace(".rc", "-rc") }}.tar.gz
  url: https://github.com/llvm/llvm-project/archive/27f30029741ecf023baece7b3dde1ff9011ffefc.tar.gz
  sha256: c54da9278c7708b64fc9a61ffe55193fea6093dc11028617a7c0dba16cb26161
  patches:
    - patches/0001-point-header-inclusion-in-lld-MachO-CMakeLists.txt-t.patch
    # backport lld bits of https://github.com/llvm/llvm-project/pull/110217
    - patches/0002-lld-LLVM_ENABLE_RUNTIMES-flang-rt.patch

build:
  number: 0
  ignore_run_exports_from:
    # not actually needed on unix
    - libxml2  # [unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - llvmdev =={{ version }}              # [build_platform != target_platform]
  host:
    - libcxx {{ cxx_compiler_version }}    # [osx]
    - llvmdev =={{ version }}
    - llvm
    # these they are present in the host env anyway as run-deps of llvm
    # and will be picked up for the build by the default settings
    - libxml2
    - zlib
    - zstd
  run:
    - {{ pin_compatible("libcxx", max_pin=None) }}  # [osx]
  run_constrained:
    - llvm =={{ version }}

test:
  commands:
    - ld.lld --version  # [linux]
    - lld-link /?  # [win]

about:
  home: https://lld.llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_file: lld/LICENSE.TXT
  summary: The LLVM Linker
  dev_url: https://github.com/llvm/llvm-project/

extra:
  recipe-maintainers:
    - isuruf
    - h-vetinari
