{% set version = "21.0.0.dev2" %}

package:
  name: lld
  version: {{ version }}

source:
  # url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-{{ version.replace(".rc", "-rc") }}.tar.gz
  url: https://github.com/llvm/llvm-project/archive/eb0f1dc00e5d0e591fe912c1aaf9dd9d01d94b8d.tar.gz
  sha256: 76ff464edb800d21d041dfe9fcfdbd05063ad71c000a2a6d9c04dd638d315e1f
  patches:
    - patches/0001-point-header-inclusion-in-lld-MachO-CMakeLists.txt-t.patch

build:
  number: 0
  ignore_run_exports_from:
    # not actually needed on unix
    - libxml2  # [unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - llvmdev =={{ version }}              # [build_platform != target_platform]
  host:
    - libcxx {{ cxx_compiler_version }}    # [osx]
    - llvmdev =={{ version }}
    - llvm
    # these they are present in the host env anyway as run-deps of llvm
    # and will be picked up for the build by the default settings
    - libxml2
    - zlib
    - zstd
  run:
    - {{ pin_compatible("libcxx", max_pin=None) }}  # [osx]
  run_constrained:
    - llvm =={{ version }}

test:
  commands:
    - ld.lld --version  # [linux]
    - lld-link /?  # [win]

about:
  home: https://lld.llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_file: lld/LICENSE.TXT
  summary: The LLVM Linker
  dev_url: https://github.com/llvm/llvm-project/

extra:
  recipe-maintainers:
    - isuruf
    - h-vetinari
