{% set version = "14.0.4" %}

package:
  name: lld
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version.replace(".rc", "-rc") }}/llvm-project-{{ version.replace(".rc", "rc") }}.src.tar.xz
  sha256: f40c77ceff02ae3873d273a51b0f93cd8e6409576f771d860d75835335522052
  patches:
    - patches/0001-point-header-inclusion-in-lld-MachO-CMakeLists.txt-t.patch

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake >=3.4.3
    - ninja    # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make     # [not win]
    - llvmdev =={{ version }}    # [build_platform != target_platform]
  host:
    - llvmdev =={{ version }}
    - llvm
    - libxml2  # [win]
    - zlib
  run_constrained:
    - llvm =={{ version }}

test:
  commands:
    - ld.lld --version  # [linux]
    - lld-link /?  # [win]

about:
  home: https://lld.llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_file: lld/LICENSE.TXT
  summary: The LLVM Linker
  dev_url: https://github.com/llvm/llvm-project/

extra:
  recipe-maintainers:
    - isuruf
    - h-vetinari
