travis:
  secure:
    BINSTAR_TOKEN: 0xNVUtk/IwXRAy3U7EVtobrmwPQ1kpKTx4RlsR+SiRn+5zcT9mKrevIyLsp4D8C+nf6oivTSfN2uKzCV6IYKxXi9H/w127ICuN3iHDNbhZEMlt3MEVHlWY9rwWkuSOsVYsFIHx7psdN4PTo8lYH1w9/okxHxnvZ/oEMbathPCIUruKMaTEcdjsqTBIC/8lrGtn7+ipmMzwJz7W4dSpEQsnSSrhOzkI2JqBoxlkN4/skQQA+xYGVzZXQ7d8xsbAO4HS1SrXaxSXFu7l1HWro9YWKHA7a0vbto2wusK+A9S3msZFQSbk5OJ6wwk1XxCy0MQfN49QY4W3ed4XoV8wYfKv6BBi8ol3iK16qqZTrKxzaD/3R1LR6sE65GjNyp3yN+KK17kwHi16M2FLNqjpdHSFcEdQHXAJ4vWGtBBQ1cMb2DnQpRuZ9X0Il05V8yXlWBwVxTq3JdX1hXKqPX4KlG/hPsK+C291hdpWmSQfXs23sr8n8NBfQ9XfP07Y3LFcTZNGmovBhpVY98eEmu1z3l7/7ZnDkIvJVDyqaMWzz8NNSKvoFcAYuK5rxDfC48pAI+QLt5uZZ9HNryzyN80RFMDfwobuELVysER/Sv6p8ooe6bcYPwulCorae2RJ2pSSAzfNcJ0wcBf9ORCfRYSWMAB0KEJQNJmy54Pk4KGC50bSY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  linux_aarch64: default
  linux_ppc64le: default

conda_forge_output_validation: true
